data:
    dvc_pull: True # pull data from dvc in code
    name: name
    path: "data/dataset.npz"

model:
    name: SimpleNet
    save_dir: "./models"
    hidden_1_size: 64
    hidden_2_size: 32

training:
    batch_size: 32
    epochs: 32
    learning_rate: 5e-2
    weight_decay: 1e-1

artifacts:
    experiment_name: iris-simple-model
    log_uri: "file:./logs/mlflow_runs"
    mlflow_server_address: "http://127.0.0.1:5000"
    # mlflow_models_uri: "file:./logs/mlflow_runs/models/"
    checkpoint:
        use: false
        dirpath: checkpoints
        filename: "{epoch:02d}-{val_loss:.4f}"
        monitor: val_loss
        save_top_k: 3
        every_n_train_steps: 20
        every_n_epochs: 1

onnx:
    feature_name: "IRIS_FEATURES" # Dict key for input_name when export to onnx
    pred_name: "CLASS_PROBS" # Dict key for output_name when export to onnx

serving:
    onnx_model_path: "auto" # Path to .onnx model. Use "auto" to automatically get trained model (after "python ./commands train" command) path.
    predictions_save_path: "./data/predictions.csv"
